### ISSUE TITLE
ffi-yajl is broken with Xcode 16 beta

### ISSUE THREAD

**Issue by hsbt** [chef/ffi-yajl#124]
Hi, I'm member of Ruby core team. I'm working to build and test Ruby runtime with the next version of macOS and Xcode.

https://bugs.ruby-lang.org/issues/20631

I found the build failure of `ffi-yajl` with Xcode 16 beta.

```
(snip)
linking shared-object ffi_yajl/ext/encoder.bundle
ld: -undefined dynamic_lookup cannot be used with -U
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This error caused with https://github.com/chef/ffi-yajl/commit/966eee23460298145bbce009ec24ef0b5b3f2f8c. This change is unnecessarily today because Apple revert the original issue from Xcode.

/cc @stanhu

**Comment by stanhu** [comment]
It sounds like we can either revert that change, or only include it if `-undefined dynamic_lookup` is not set?

**Comment by hsbt** [comment]
Fortunately, Xcode 16 beta 4 is fixed linker with `-U` option.
