### ISSUE TITLE
build on debian

### ISSUE THREAD

**Issue by h4ck3rm1k3** [chef/ffi-yajl#70]
I have patched the code to use usr local lib
https://github.com/h4ck3rm1k3/ffi-yajl/commit/11e2942b8e6954147533cf2a7f0ecc8245c71728

I could not get this to compile on debian unstable. 

this module was not installing either libyajl2-gem

compiled and installed git@github.com:lloyd/yajl.git and used that.

**Comment by lamont-granquist** [comment]
you can already set USE_SYSTEM_LIBYAJL2 to do this 

https://github.com/chef/ffi-yajl#yajl-library-packaging
