### ISSUE TITLE
Cannot install on CentOS 7.2: cannot load such file -- libyajl2 (LoadError)

### ISSUE THREAD

**Issue by ephracis** [chef/ffi-yajl#76]
I am trying to install this gem on CentOS 7.2 but encounter this error:

    /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- libyajl2 (LoadError)

I have installed yajl:

    sudo yum install yajl-devel

**Comment by lamont-granquist** [comment]
you need to have the libyajl2-gem installed `gem install libyajl2`
