### ISSUE TITLE
Unable to install ffi-yajl -v '1.4.0'

### ISSUE THREAD

**Issue by Giriraj24** [chef/ffi-yajl#77]
Hi All,

I am using **windows 7** and I have my **chefdk installed. and Ruby is part of my chefdk(No other ruby I have).**

When I am running from **"bundle install"** from my cookbook, then it runs fine until when it comes to the point where it has to install ffi-yajl -v '1.4.0' and it throws the error and ask me to do "gem install ffi-yajl -v '1.4.0'". When I try running  "gem install ffi-yajl -v '1.4.0'" then I get the following error:

```
**######################################################################**
PS > **gem install ffi-yajl -v '1.4.0'**
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing ffi-yajl:
        ERROR: Failed to build gem native extension.

    current directory: C:/Users/54223345/AppData/Local/chefdk/gem/ruby/2.1.0/gems/ffi-yajl-1.4.0/ext/ffi_yajl/ext/encod
er
C:/opscode/chefdk/embedded/bin/ruby.exe -r ./siteconf20160606-8528-1354lfu.rb extconf.rb
 -IC:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/include -IC:/opscod
e/chefdk/embedded/include -O3 -march=i686 -DFD_SETSIZE=2048
 -LC:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/lib -L. -LC:/opscod
e/chefdk/embedded/lib
creating Makefile

current directory: C:/Users/54223345/AppData/Local/chefdk/gem/ruby/2.1.0/gems/ffi-yajl-1.4.0/ext/ffi_yajl/ext/encoder
make "DESTDIR=" clean

current directory: C:/Users/54223345/AppData/Local/chefdk/gem/ruby/2.1.0/gems/ffi-yajl-1.4.0/ext/ffi_yajl/ext/encoder
make "DESTDIR="
generating encoder-i386-mingw32.def
compiling encoder.c
linking shared-object ffi_yajl/ext/encoder.so
c:/opscode/chefdk/embedded/mingw/bin/../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot f
ind -lyajldll
collect2.exe: error: ld returned 1 exit status
make: *** [encoder.so] Error 1

make failed, exit code 2

Gem files will remain installed in C:/Users/54223345/AppData/Local/chefdk/gem/ruby/2.1.0/gems/ffi-yajl-1.4.0 for inspec
tion.
Results logged to C:/Users/54223345/AppData/Local/chefdk/gem/ruby/2.1.0/extensions/x86-mingw32/2.1.0/ffi-yajl-1.4.0/gem

**######################################################################**
```

I tried all possible mean available in google but none helped. Please help, I have been struggling with this from last 3 months.

**Comment by Giriraj24** [comment]
Following are the versions of binaries I am using:

**gem --version**
2.6.4
**ruby --version**
ruby 2.1.8p440 
**bundle --version**
Bundler version 1.11.2

**Comment by lamont-granquist** [comment]
what is the output of `gem install libyajl2`?  what is the contents of `C:/Users/54223345/AppData/Local/chefdk/gem/ruby/2.1.0/extensions/x86-mingw32/2.1.0/ffi-yajl-1.4.0/gem_make.out`?

**Comment by lamont-granquist** [comment]
ffi-yajl 1.4.0 is from February 17, 2015  which is getting on to nearly 18 months ago.

its likely time to upgrade your chef-client

**Comment by DavidTNguyen** [comment]
Same error with ChefDK v0.16.28.  This Gem is a trouble child.

**Comment by DavidTNguyen** [comment]
The following sequence solved the issue for me
1> gem install libyajl2
2> gem update -i  C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0 ffi-yajl
3> bundle install
