### ISSUE TITLE
Which Ruby version could install ffi-yajl?

### ISSUE THREAD

**Issue by jptomo** [chef/ffi-yajl#90]
[ffi-yajl.gemspec.shared Line 15](https://github.com/chef/ffi-yajl/blob/2.3.1/ffi-yajl.gemspec.shared#L15) tells me this gem install under upper Ruby 2.2.

But README.md tells me Ruby MRI 1.9.3/2.0.0/2.1.x/2.2.x on CentOS7.

Which is correct?

# Environment

* CentOS Linux release 7.3.1611 (Core)
* install ruby==2.0.0.648, ruby-devel==2.0.0.648, rubygem-bundler==1.7.8 by yum

**Comment by lamont-granquist** [comment]
README updated to "Ruby 2.2+ and compatible rbx or jruby"

**Comment by jptomo** [comment]
thx
