### ISSUE TITLE
never bump required ruby versions in a patch release

### ISSUE THREAD

**Issue by logicminds** [chef/ffi-yajl#92]
I know you want to force users to upgrade to ruby 2.2, but many of us cannot upgrade to a newer version of ruby yet. Can you undo 2.3.1 and release 2.3.2 with the ruby version requirement set to back to `>=2.1`.

If you need to upgrade ruby please do so in a minor release (2.4) or better yet a major release 3.0
as a patch release should never break existing environments. 

See the semantic versioning guide
http://guides.rubygems.org/patterns/

https://github.com/chef/ffi-yajl/blob/master/ffi-yajl.gemspec.shared#L15

**Comment by coderanger** [comment]
@logicminds We don't generally consider something to be compat breaking if the only versions of a thing affected are EOL'd. That's kind of the definition of EOL.

**Comment by logicminds** [comment]
It is a breaking change though.  Anyone who has `'gem 'ffi-yajl', "=~ 2.3.0"` in their gemfile and not using ruby 2.2+ now has a problem.    I am not even using this gem directly and it caused a problem for me.  Please explain what bug you were fixing in this codebase that forced you to roll a patch version instead of a minor version for a runtime version change?  Does ffi-yajl 2.3.1 actually require 2.2  whereas ffi-yajl 2.3.0 did not?  The answer is no.  What is the minimum runtime dependency for this codebase where code works?  Was there some other hidden agenda here?  Do other libraries just all the sudden drop support for runtimes or operating systems in a patch release as well?  Is this consistent across other chef gems?

**Comment by coderanger** [comment]
Anyone not using 2.2+ is definitionally no longer supported. Again, that's what End Of Life means, you can't actually keep using it and assume things will just work. If you stay time-locked it won't break, but any upgrades of _anything_ should be considered potentially breaking.
